### ISSUE TITLE
用fp32精度微调文本生成模型不收敛

### ISSUE THREAD

**Issue by zmingshi** [TsinghuaAI/CPM-1-Finetune#20]
问题描述：散文数据集finetune 文本生成，loss 一直在7.0 左右附近波动，没有下降的趋势。

微调环境：

8 * Tesla V100
cuda 10.2
pytorch 1.6.0
训练代码是基于finetune_child.py 做了简单修改
生成模版比较简单：`散文正文 + <eod>`,   限制每条样本最长不超过1024.
```python
    def process(self, data):
        """
        处理一批数据，适合小数据一次性载入内存
        """
        samples, sizes = [], []
        for d in tqdm(data[:int(self.ratio * len(data))], disable=(torch.distributed.get_rank() != 0)):
            # Loss mask. # loss mask 全1
            loss_mask = [1] * (len(d["sent"]) - 1)
            samples.append({
                "input_ids": d["sent"][:-1],  # ids for the tokenized sentence
                "labels": d["sent"][1:],  # token labels of each sentence
                "loss_mask": loss_mask,  # mask of the loss
            })
            sizes.append(len(d["sent"]))

        return samples, sizes

    def collate(self, x):
        batch_size = len(x)
        samples = [s[0] for s in x]

        # fit to the max_size
        max_size = self.max_size

        # triangle attention mask
        attn_mask = torch.tril(torch.ones((max_size, max_size))).unsqueeze(0)
        position_ids = torch.arange(max_size, dtype=torch.long).unsqueeze(0).repeat(batch_size, 1)

        if self.args.fp16:
            attn_mask = attn_mask.half()

        # the data that need to go through the model
        batch_sample = {
            "input_ids": torch.ones(batch_size, max_size).long() * self.pad_id,
            "attention_mask": attn_mask.unsqueeze(1),
            "position_ids": position_ids,
        }

        # the data that do not need to go through the model
        no_model_sample = {
            "labels": torch.ones(batch_size, max_size).long() * self.pad_id,
            "loss_mask": torch.zeros(batch_size, max_size).float()
        }

        for i, samp in enumerate(samples):
            batch_sample["input_ids"][i, :len(samp["input_ids"])] = torch.tensor(samp["input_ids"])
            no_model_sample["labels"][i, :len(samp["labels"])] = torch.tensor(samp["labels"])
            no_model_sample["loss_mask"][i, :len(samp["loss_mask"])] = torch.tensor(samp["loss_mask"])

        return batch_sample, no_model_sample
```

```python
           # loss 计算
            for batch, no_model_batch in tqdm(train_dataloader, disable=(torch.distributed.get_rank() != 0)):
                for k in batch:
                    batch[k] = batch[k].to(device)
                for k in no_model_batch:
                    no_model_batch[k] = no_model_batch[k].to(device)

                output = model(**batch)
                # get the loss of the valid tokens
                loss_mask = no_model_batch["loss_mask"]
                output = output * no_model_batch["loss_mask"].unsqueeze(-1)
                # get the label of the last token
                labels = (no_model_batch["labels"].float() * loss_mask).long()

                # cross_entropy loss
                losses = mpu.vocab_parallel_cross_entropy(output.contiguous().float(), labels)
                loss = torch.mean(losses)

                model.backward(loss)
                model.step()

                torch.distributed.all_reduce(loss.data, group=mpu.get_data_parallel_group())
                loss.data = loss.data / mpu.get_data_parallel_world_size()
                total_loss += loss.item() / grad_acc
```
训练数据600w 左右，batch_size=4， 其余参数包括 ds_finetune_large_fp32.json 均和官方的保持一致，未做修改。现在迭代了8700多步，loss 完全没有下降的趋势～ 
感觉散文生成这个场景应该比较接近pretrain, loss 应该下降较快，不知道有什么问题？烦请解答～

```
Epoch 0, global step 10, total step 2530770, train lm loss: 6.420628082752228
Epoch 0, global step 20, total step 2530770, train lm loss: 6.984822225570679
Epoch 0, global step 30, total step 2530770, train lm loss: 6.933394753932953
Epoch 0, global step 40, total step 2530770, train lm loss: 7.0079732775688175
Epoch 0, global step 50, total step 2530770, train lm loss: 6.921390330791473
Epoch 0, global step 60, total step 2530770, train lm loss: 7.001181125640869
Epoch 0, global step 70, total step 2530770, train lm loss: 7.04995551109314
Epoch 0, global step 80, total step 2530770, train lm loss: 6.945537781715393
Epoch 0, global step 90, total step 2530770, train lm loss: 7.042714178562164
Epoch 0, global step 100, total step 2530770, train lm loss: 6.971484804153443
Epoch 0, global step 110, total step 2530770, train lm loss: 7.005775141716003
Epoch 0, global step 120, total step 2530770, train lm loss: 7.062895143032074
...

Epoch 0, global step 4100, total step 2530770, train lm loss: 6.946014547348023
Epoch 0, global step 4110, total step 2530770, train lm loss: 6.916108274459839
Epoch 0, global step 4120, total step 2530770, train lm loss: 6.919975912570953
Epoch 0, global step 4130, total step 2530770, train lm loss: 7.016709792613983
Epoch 0, global step 4140, total step 2530770, train lm loss: 6.910797345638275
Epoch 0, global step 4150, total step 2530770, train lm loss: 6.961629819869995
Epoch 0, global step 4160, total step 2530770, train lm loss: 7.042662894725799
Epoch 0, global step 4170, total step 2530770, train lm loss: 6.9127843379974365
Epoch 0, global step 4180, total step 2530770, train lm loss: 6.967308390140533
Epoch 0, global step 4190, total step 2530770, train lm loss: 7.014726150035858
Epoch 0, global step 4200, total step 2530770, train lm loss: 7.040352630615234
Epoch 0, global step 4210, total step 2530770, train lm loss: 6.956566846370697
Epoch 0, global step 4220, total step 2530770, train lm loss: 6.892919874191284
Epoch 0, global step 4230, total step 2530770, train lm loss: 6.966098439693451
Epoch 0, global step 4240, total step 2530770, train lm loss: 6.866201710700989
Epoch 0, global step 4250, total step 2530770, train lm loss: 6.866942071914673
Epoch 0, global step 4260, total step 2530770, train lm loss: 6.877177131175995
Epoch 0, global step 4270, total step 2530770, train lm loss: 6.901149475574494
...
Epoch 0, global step 8600, total step 2530770, train lm loss: 6.9025374293327335
Epoch 0, global step 8610, total step 2530770, train lm loss: 6.960937476158142
Epoch 0, global step 8620, total step 2530770, train lm loss: 6.924565947055816
Epoch 0, global step 8630, total step 2530770, train lm loss: 6.928597915172577
Epoch 0, global step 8640, total step 2530770, train lm loss: 6.967922806739807
Epoch 0, global step 8650, total step 2530770, train lm loss: 6.922226631641388
Epoch 0, global step 8660, total step 2530770, train lm loss: 6.962999868392944
Epoch 0, global step 8670, total step 2530770, train lm loss: 6.888333117961883
Epoch 0, global step 8680, total step 2530770, train lm loss: 6.876088976860046
Epoch 0, global step 8690, total step 2530770, train lm loss: 6.996463882923126
Epoch 0, global step 8700, total step 2530770, train lm loss: 6.965291225910187
Epoch 0, global step 8710, total step 2530770, train lm loss: 6.952336919307709
Epoch 0, global step 8720, total step 2530770, train lm loss: 6.912003934383392
Epoch 0, global step 8730, total step 2530770, train lm loss: 6.955647802352905
Epoch 0, global step 8740, total step 2530770, train lm loss: 7.019775640964508
```

**Comment by t1101675** [comment]
感谢您的关注！我们将微调 STC 对话数据集的相关代码更新到了仓库中，并且对原来仓库的代码进行了一些整理。我们观察在 STC 对话数据集上 loss 是可以正常下降的。并且在我们内部的一个小说长文本数据集上也可以正常下降。您可以对照我们实现检查一下。

**Comment by zmingshi** [comment]
> 感谢您的关注！我们将微调 STC 对话数据集的相关代码更新到了仓库中，并且对原来仓库的代码进行了一些整理。我们观察在 STC 对话数据集上 loss 是可以正常下降的。并且在我们内部的一个小说长文本数据集上也可以正常下降。您可以对照我们实现检查一下。

@t1101675 感谢公布stc训练相关代码数据，目前运行基本符合预期，loss 也是缓慢下降的。但是有一个小问题，就是在我的文本数据上，一个epoch 结束后，开启新的epoch 训练时，训练集loss 会有一次突然上升，这可能是什么原因呢？
```shell
Epoch 0, global step 5530, total step 450010, train lm loss: 1.992294266819954
 98%|█████████▊| 44312/45001 [50:17:58<47:14,  4.11s/it]
Epoch 0, global step 5540, total step 450010, train lm loss: 1.9755227208137511
 99%|█████████▊| 44392/45001 [50:23:23<41:40,  4.11s/it]
Epoch 0, global step 5550, total step 450010, train lm loss: 1.9841984316706658
 99%|█████████▉| 44472/45001 [50:28:49<36:11,  4.11s/it]
Epoch 0, global step 5560, total step 450010, train lm loss: 1.9951681569218636
 99%|█████████▉| 44552/45001 [50:34:14<30:43,  4.10s/it]
Epoch 0, global step 5570, total step 450010, train lm loss: 1.9766493245959282
 99%|█████████▉| 44632/45001 [50:39:39<25:12,  4.10s/it]
Epoch 0, global step 5580, total step 450010, train lm loss: 1.998405297100544
 99%|█████████▉| 44712/45001 [50:45:04<19:50,  4.12s/it]
Epoch 0, global step 5590, total step 450010, train lm loss: 1.9913148269057275
100%|█████████▉| 44792/45001 [50:50:30<14:17,  4.10s/it]
Epoch 0, global step 5600, total step 450010, train lm loss: 1.9937419578433038
100%|█████████▉| 44872/45001 [50:55:55<08:51,  4.12s/it]
Epoch 0, global step 5610, total step 450010, train lm loss: 1.9915068462491035
100%|█████████▉| 44952/45001 [51:01:20<03:21,  4.12s/it]
Epoch 0, global step 5620, total step 450010, train lm loss: 1.9987193062901496
100%|██████████| 45001/45001 [51:04:41<00:00,  4.09s/it]
  0%|          | 31/45001 [02:12<52:11:06,  4.18s/it]
Epoch 1, global step 5630, total step 450010, train lm loss: 2.013618862628937
  0%|          | 111/45001 [07:43<52:07:18,  4.18s/it]
Epoch 1, global step 5640, total step 450010, train lm loss: 2.0521092385053636
  0%|          | 191/45001 [13:13<51:58:24,  4.18s/it]
Epoch 1, global step 5650, total step 450010, train lm loss: 2.0431797206401825
  1%|          | 271/45001 [18:43<51:48:27,  4.17s/it]
Epoch 1, global step 5660, total step 450010, train lm loss: 2.043635682761669
  1%|          | 351/45001 [24:13<51:42:37,  4.17s/it]
Epoch 1, global step 5670, total step 450010, train lm loss: 2.066113193333149
  1%|          | 431/45001 [29:43<51:40:46,  4.17s/it]
Epoch 1, global step 5680, total step 450010, train lm loss: 2.0617008179426195
  1%|          | 511/45001 [35:13<51:35:36,  4.17s/it]
Epoch 1, global step 5690, total step 450010, train lm loss: 2.0475533291697503
  1%|▏         | 591/45001 [40:43<51:29:45,  4.17s/it]
Epoch 1, global step 5700, total step 450010, train lm loss: 2.039434751868248
  1%|▏         | 671/45001 [46:13<51:22:55,  4.17s/it]
Epoch 1, global step 5710, total step 450010, train lm loss: 2.0422093361616134
  2%|▏         | 751/45001 [51:43<51:26:29,  4.19s/it]
Epoch 1, global step 5720, total step 450010, train lm loss: 2.0543945729732513
....................
Epoch 1, global step 11130, total step 450010, train lm loss: 1.7039588585495948
 98%|█████████▊| 44111/45001 [49:56:41<1:01:01,  4.11s/it]
Epoch 1, global step 11140, total step 450010, train lm loss: 1.6935658752918243
 98%|█████████▊| 44191/45001 [50:02:06<55:31,  4.11s/it]
Epoch 1, global step 11150, total step 450010, train lm loss: 1.7021886244416238
 98%|█████████▊| 44271/45001 [50:07:31<50:05,  4.12s/it]
Epoch 1, global step 11160, total step 450010, train lm loss: 1.6594394057989121
 99%|█████████▊| 44351/45001 [50:12:56<44:25,  4.10s/it]
Epoch 1, global step 11170, total step 450010, train lm loss: 1.6883946016430855
 99%|█████████▊| 44431/45001 [50:18:21<39:02,  4.11s/it]
Epoch 1, global step 11180, total step 450010, train lm loss: 1.6596121966838837
 99%|█████████▉| 44511/45001 [50:23:47<33:37,  4.12s/it]
Epoch 1, global step 11190, total step 450010, train lm loss: 1.7075278133153915
 99%|█████████▉| 44591/45001 [50:29:12<28:07,  4.12s/it]
Epoch 1, global step 11200, total step 450010, train lm loss: 1.6892587140202522
 99%|█████████▉| 44671/45001 [50:34:37<22:39,  4.12s/it]
Epoch 1, global step 11210, total step 450010, train lm loss: 1.6789431631565095
 99%|█████████▉| 44751/45001 [50:40:03<17:05,  4.10s/it]
Epoch 1, global step 11220, total step 450010, train lm loss: 1.701674534380436
100%|█████████▉| 44831/45001 [50:45:28<11:39,  4.12s/it]
Epoch 1, global step 11230, total step 450010, train lm loss: 1.6943398639559746
100%|█████████▉| 44911/45001 [50:50:53<06:10,  4.11s/it]
Epoch 1, global step 11240, total step 450010, train lm loss: 1.6946084380149842
100%|█████████▉| 44991/45001 [50:56:19<00:41,  4.11s/it]
Epoch 1, global step 11250, total step 450010, train lm loss: 1.7021038860082627
100%|██████████| 45001/45001 [50:57:02<00:00,  4.08s/it]
  0%|          | 70/45001 [04:53<52:01:53,  4.17s/it]
Epoch 2, global step 11260, total step 450010, train lm loss: 1.8552434042096138
  0%|          | 150/45001 [10:24<51:59:49,  4.17s/it]
Epoch 2, global step 11270, total step 450010, train lm loss: 1.8739720791578294
  1%|          | 230/45001 [15:54<51:47:23,  4.16s/it]
Epoch 2, global step 11280, total step 450010, train lm loss: 1.8646982133388519
  1%|          | 310/45001 [21:24<51:47:50,  4.17s/it]
Epoch 2, global step 11290, total step 450010, train lm loss: 1.895784465968609
  1%|          | 390/45001 [26:54<51:50:56,  4.18s/it]
Epoch 2, global step 11300, total step 450010, train lm loss: 1.8786763593554496
  1%|          | 470/45001 [32:24<51:36:17,  4.17s/it]
Epoch 2, global step 11310, total step 450010, train lm loss: 1.889454485476017
  1%|          | 550/45001 [37:54<51:27:44,  4.17s/it]
Epoch 2, global step 11320, total step 450010, train lm loss: 1.8542711272835732
  1%|▏         | 630/45001 [43:25<51:25:46,  4.17s/it]
Epoch 2, global step 11330, total step 450010, train lm loss: 1.8668335244059562

```

**Comment by JiamingUWU** [comment]
> > 感谢您的关注！我们将微调 STC 对话数据集的相关代码更新到了仓库中，并且对原来仓库的代码进行了一些整理。我们观察在 STC 对话数据集上 loss 是可以正常下降的。并且在我们内部的一个小说长文本数据集上也可以正常下降。您可以对照我们实现检查一下。
> 
> @t1101675 感谢公布stc训练相关代码数据，目前运行基本符合预期，loss 也是缓慢下降的。但是有一个小问题，就是在我的文本数据上，一个epoch 结束后，开启新的epoch 训练时，训练集loss 会有一次突然上升(0到1略有上升，1到2上升明显)，这可能是什么原因呢？
> 
> ```shell
> Epoch 0, global step 5530, total step 450010, train lm loss: 1.992294266819954
>  98%|█████████▊| 44312/45001 [50:17:58<47:14,  4.11s/it]
> Epoch 0, global step 5540, total step 450010, train lm loss: 1.9755227208137511
>  99%|█████████▊| 44392/45001 [50:23:23<41:40,  4.11s/it]
> Epoch 0, global step 5550, total step 450010, train lm loss: 1.9841984316706658
>  99%|█████████▉| 44472/45001 [50:28:49<36:11,  4.11s/it]
> Epoch 0, global step 5560, total step 450010, train lm loss: 1.9951681569218636
>  99%|█████████▉| 44552/45001 [50:34:14<30:43,  4.10s/it]
> Epoch 0, global step 5570, total step 450010, train lm loss: 1.9766493245959282
>  99%|█████████▉| 44632/45001 [50:39:39<25:12,  4.10s/it]
> Epoch 0, global step 5580, total step 450010, train lm loss: 1.998405297100544
>  99%|█████████▉| 44712/45001 [50:45:04<19:50,  4.12s/it]
> Epoch 0, global step 5590, total step 450010, train lm loss: 1.9913148269057275
> 100%|█████████▉| 44792/45001 [50:50:30<14:17,  4.10s/it]
> Epoch 0, global step 5600, total step 450010, train lm loss: 1.9937419578433038
> 100%|█████████▉| 44872/45001 [50:55:55<08:51,  4.12s/it]
> Epoch 0, global step 5610, total step 450010, train lm loss: 1.9915068462491035
> 100%|█████████▉| 44952/45001 [51:01:20<03:21,  4.12s/it]
> Epoch 0, global step 5620, total step 450010, train lm loss: 1.9987193062901496
> 100%|██████████| 45001/45001 [51:04:41<00:00,  4.09s/it]
>   0%|          | 31/45001 [02:12<52:11:06,  4.18s/it]
> Epoch 1, global step 5630, total step 450010, train lm loss: 2.013618862628937
>   0%|          | 111/45001 [07:43<52:07:18,  4.18s/it]
> Epoch 1, global step 5640, total step 450010, train lm loss: 2.0521092385053636
>   0%|          | 191/45001 [13:13<51:58:24,  4.18s/it]
> Epoch 1, global step 5650, total step 450010, train lm loss: 2.0431797206401825
>   1%|          | 271/45001 [18:43<51:48:27,  4.17s/it]
> Epoch 1, global step 5660, total step 450010, train lm loss: 2.043635682761669
>   1%|          | 351/45001 [24:13<51:42:37,  4.17s/it]
> Epoch 1, global step 5670, total step 450010, train lm loss: 2.066113193333149
>   1%|          | 431/45001 [29:43<51:40:46,  4.17s/it]
> Epoch 1, global step 5680, total step 450010, train lm loss: 2.0617008179426195
>   1%|          | 511/45001 [35:13<51:35:36,  4.17s/it]
> Epoch 1, global step 5690, total step 450010, train lm loss: 2.0475533291697503
>   1%|▏         | 591/45001 [40:43<51:29:45,  4.17s/it]
> Epoch 1, global step 5700, total step 450010, train lm loss: 2.039434751868248
>   1%|▏         | 671/45001 [46:13<51:22:55,  4.17s/it]
> Epoch 1, global step 5710, total step 450010, train lm loss: 2.0422093361616134
>   2%|▏         | 751/45001 [51:43<51:26:29,  4.19s/it]
> Epoch 1, global step 5720, total step 450010, train lm loss: 2.0543945729732513
> 
> 
> ....................
> 
> 
> Epoch 1, global step 11130, total step 450010, train lm loss: 1.7039588585495948
>  98%|█████████▊| 44111/45001 [49:56:41<1:01:01,  4.11s/it]
> Epoch 1, global step 11140, total step 450010, train lm loss: 1.6935658752918243
>  98%|█████████▊| 44191/45001 [50:02:06<55:31,  4.11s/it]
> Epoch 1, global step 11150, total step 450010, train lm loss: 1.7021886244416238
>  98%|█████████▊| 44271/45001 [50:07:31<50:05,  4.12s/it]
> Epoch 1, global step 11160, total step 450010, train lm loss: 1.6594394057989121
>  99%|█████████▊| 44351/45001 [50:12:56<44:25,  4.10s/it]
> Epoch 1, global step 11170, total step 450010, train lm loss: 1.6883946016430855
>  99%|█████████▊| 44431/45001 [50:18:21<39:02,  4.11s/it]
> Epoch 1, global step 11180, total step 450010, train lm loss: 1.6596121966838837
>  99%|█████████▉| 44511/45001 [50:23:47<33:37,  4.12s/it]
> Epoch 1, global step 11190, total step 450010, train lm loss: 1.7075278133153915
>  99%|█████████▉| 44591/45001 [50:29:12<28:07,  4.12s/it]
> Epoch 1, global step 11200, total step 450010, train lm loss: 1.6892587140202522
>  99%|█████████▉| 44671/45001 [50:34:37<22:39,  4.12s/it]
> Epoch 1, global step 11210, total step 450010, train lm loss: 1.6789431631565095
>  99%|█████████▉| 44751/45001 [50:40:03<17:05,  4.10s/it]
> Epoch 1, global step 11220, total step 450010, train lm loss: 1.701674534380436
> 100%|█████████▉| 44831/45001 [50:45:28<11:39,  4.12s/it]
> Epoch 1, global step 11230, total step 450010, train lm loss: 1.6943398639559746
> 100%|█████████▉| 44911/45001 [50:50:53<06:10,  4.11s/it]
> Epoch 1, global step 11240, total step 450010, train lm loss: 1.6946084380149842
> 100%|█████████▉| 44991/45001 [50:56:19<00:41,  4.11s/it]
> Epoch 1, global step 11250, total step 450010, train lm loss: 1.7021038860082627
> 100%|██████████| 45001/45001 [50:57:02<00:00,  4.08s/it]
>   0%|          | 70/45001 [04:53<52:01:53,  4.17s/it]
> Epoch 2, global step 11260, total step 450010, train lm loss: 1.8552434042096138
>   0%|          | 150/45001 [10:24<51:59:49,  4.17s/it]
> Epoch 2, global step 11270, total step 450010, train lm loss: 1.8739720791578294
>   1%|          | 230/45001 [15:54<51:47:23,  4.16s/it]
> Epoch 2, global step 11280, total step 450010, train lm loss: 1.8646982133388519
>   1%|          | 310/45001 [21:24<51:47:50,  4.17s/it]
> Epoch 2, global step 11290, total step 450010, train lm loss: 1.895784465968609
>   1%|          | 390/45001 [26:54<51:50:56,  4.18s/it]
> Epoch 2, global step 11300, total step 450010, train lm loss: 1.8786763593554496
>   1%|          | 470/45001 [32:24<51:36:17,  4.17s/it]
> Epoch 2, global step 11310, total step 450010, train lm loss: 1.889454485476017
>   1%|          | 550/45001 [37:54<51:27:44,  4.17s/it]
> Epoch 2, global step 11320, total step 450010, train lm loss: 1.8542711272835732
>   1%|▏         | 630/45001 [43:25<51:25:46,  4.17s/it]
> Epoch 2, global step 11330, total step 450010, train lm loss: 1.8668335244059562
> ```

我是这样理解的，不知道是否准确，在epoch 1内部中，对于每个batch，模型只见过一次数据，而在epoch2中，模型见过两次数据，因此epoch2和epoch1的loss会有一个明显下降，而epoch内部差异不大

**Comment by zmingshi** [comment]
> > > 感谢您的关注！我们将微调 STC 对话数据集的相关代码更新到了仓库中，并且对原来仓库的代码进行了一些整理。我们观察在 STC 对话数据集上 loss 是可以正常下降的。并且在我们内部的一个小说长文本数据集上也可以正常下降。您可以对照我们实现检查一下。
> > 
> > 
> > @t1101675 感谢公布stc训练相关代码数据，目前运行基本符合预期，loss 也是缓慢下降的。但是有一个小问题，就是在我的文本数据上，一个epoch 结束后，开启新的epoch 训练时，训练集loss 会有一次突然上升(0到1略有上升，1到2上升明显)，这可能是什么原因呢？
> > ```shell
> > Epoch 0, global step 5530, total step 450010, train lm loss: 1.992294266819954
> >  98%|█████████▊| 44312/45001 [50:17:58<47:14,  4.11s/it]
> > Epoch 0, global step 5540, total step 450010, train lm loss: 1.9755227208137511
> >  99%|█████████▊| 44392/45001 [50:23:23<41:40,  4.11s/it]
> > Epoch 0, global step 5550, total step 450010, train lm loss: 1.9841984316706658
> >  99%|█████████▉| 44472/45001 [50:28:49<36:11,  4.11s/it]
> > Epoch 0, global step 5560, total step 450010, train lm loss: 1.9951681569218636
> >  99%|█████████▉| 44552/45001 [50:34:14<30:43,  4.10s/it]
> > Epoch 0, global step 5570, total step 450010, train lm loss: 1.9766493245959282
> >  99%|█████████▉| 44632/45001 [50:39:39<25:12,  4.10s/it]
> > Epoch 0, global step 5580, total step 450010, train lm loss: 1.998405297100544
> >  99%|█████████▉| 44712/45001 [50:45:04<19:50,  4.12s/it]
> > Epoch 0, global step 5590, total step 450010, train lm loss: 1.9913148269057275
> > 100%|█████████▉| 44792/45001 [50:50:30<14:17,  4.10s/it]
> > Epoch 0, global step 5600, total step 450010, train lm loss: 1.9937419578433038
> > 100%|█████████▉| 44872/45001 [50:55:55<08:51,  4.12s/it]
> > Epoch 0, global step 5610, total step 450010, train lm loss: 1.9915068462491035
> > 100%|█████████▉| 44952/45001 [51:01:20<03:21,  4.12s/it]
> > Epoch 0, global step 5620, total step 450010, train lm loss: 1.9987193062901496
> > 100%|██████████| 45001/45001 [51:04:41<00:00,  4.09s/it]
> >   0%|          | 31/45001 [02:12<52:11:06,  4.18s/it]
> > Epoch 1, global step 5630, total step 450010, train lm loss: 2.013618862628937
> >   0%|          | 111/45001 [07:43<52:07:18,  4.18s/it]
> > Epoch 1, global step 5640, total step 450010, train lm loss: 2.0521092385053636
> >   0%|          | 191/45001 [13:13<51:58:24,  4.18s/it]
> > Epoch 1, global step 5650, total step 450010, train lm loss: 2.0431797206401825
> >   1%|          | 271/45001 [18:43<51:48:27,  4.17s/it]
> > Epoch 1, global step 5660, total step 450010, train lm loss: 2.043635682761669
> >   1%|          | 351/45001 [24:13<51:42:37,  4.17s/it]
> > Epoch 1, global step 5670, total step 450010, train lm loss: 2.066113193333149
> >   1%|          | 431/45001 [29:43<51:40:46,  4.17s/it]
> > Epoch 1, global step 5680, total step 450010, train lm loss: 2.0617008179426195
> >   1%|          | 511/45001 [35:13<51:35:36,  4.17s/it]
> > Epoch 1, global step 5690, total step 450010, train lm loss: 2.0475533291697503
> >   1%|▏         | 591/45001 [40:43<51:29:45,  4.17s/it]
> > Epoch 1, global step 5700, total step 450010, train lm loss: 2.039434751868248
> >   1%|▏         | 671/45001 [46:13<51:22:55,  4.17s/it]
> > Epoch 1, global step 5710, total step 450010, train lm loss: 2.0422093361616134
> >   2%|▏         | 751/45001 [51:43<51:26:29,  4.19s/it]
> > Epoch 1, global step 5720, total step 450010, train lm loss: 2.0543945729732513
> > 
> > 
> > ....................
> > 
> > 
> > Epoch 1, global step 11130, total step 450010, train lm loss: 1.7039588585495948
> >  98%|█████████▊| 44111/45001 [49:56:41<1:01:01,  4.11s/it]
> > Epoch 1, global step 11140, total step 450010, train lm loss: 1.6935658752918243
> >  98%|█████████▊| 44191/45001 [50:02:06<55:31,  4.11s/it]
> > Epoch 1, global step 11150, total step 450010, train lm loss: 1.7021886244416238
> >  98%|█████████▊| 44271/45001 [50:07:31<50:05,  4.12s/it]
> > Epoch 1, global step 11160, total step 450010, train lm loss: 1.6594394057989121
> >  99%|█████████▊| 44351/45001 [50:12:56<44:25,  4.10s/it]
> > Epoch 1, global step 11170, total step 450010, train lm loss: 1.6883946016430855
> >  99%|█████████▊| 44431/45001 [50:18:21<39:02,  4.11s/it]
> > Epoch 1, global step 11180, total step 450010, train lm loss: 1.6596121966838837
> >  99%|█████████▉| 44511/45001 [50:23:47<33:37,  4.12s/it]
> > Epoch 1, global step 11190, total step 450010, train lm loss: 1.7075278133153915
> >  99%|█████████▉| 44591/45001 [50:29:12<28:07,  4.12s/it]
> > Epoch 1, global step 11200, total step 450010, train lm loss: 1.6892587140202522
> >  99%|█████████▉| 44671/45001 [50:34:37<22:39,  4.12s/it]
> > Epoch 1, global step 11210, total step 450010, train lm loss: 1.6789431631565095
> >  99%|█████████▉| 44751/45001 [50:40:03<17:05,  4.10s/it]
> > Epoch 1, global step 11220, total step 450010, train lm loss: 1.701674534380436
> > 100%|█████████▉| 44831/45001 [50:45:28<11:39,  4.12s/it]
> > Epoch 1, global step 11230, total step 450010, train lm loss: 1.6943398639559746
> > 100%|█████████▉| 44911/45001 [50:50:53<06:10,  4.11s/it]
> > Epoch 1, global step 11240, total step 450010, train lm loss: 1.6946084380149842
> > 100%|█████████▉| 44991/45001 [50:56:19<00:41,  4.11s/it]
> > Epoch 1, global step 11250, total step 450010, train lm loss: 1.7021038860082627
> > 100%|██████████| 45001/45001 [50:57:02<00:00,  4.08s/it]
> >   0%|          | 70/45001 [04:53<52:01:53,  4.17s/it]
> > Epoch 2, global step 11260, total step 450010, train lm loss: 1.8552434042096138
> >   0%|          | 150/45001 [10:24<51:59:49,  4.17s/it]
> > Epoch 2, global step 11270, total step 450010, train lm loss: 1.8739720791578294
> >   1%|          | 230/45001 [15:54<51:47:23,  4.16s/it]
> > Epoch 2, global step 11280, total step 450010, train lm loss: 1.8646982133388519
> >   1%|          | 310/45001 [21:24<51:47:50,  4.17s/it]
> > Epoch 2, global step 11290, total step 450010, train lm loss: 1.895784465968609
> >   1%|          | 390/45001 [26:54<51:50:56,  4.18s/it]
> > Epoch 2, global step 11300, total step 450010, train lm loss: 1.8786763593554496
> >   1%|          | 470/45001 [32:24<51:36:17,  4.17s/it]
> > Epoch 2, global step 11310, total step 450010, train lm loss: 1.889454485476017
> >   1%|          | 550/45001 [37:54<51:27:44,  4.17s/it]
> > Epoch 2, global step 11320, total step 450010, train lm loss: 1.8542711272835732
> >   1%|▏         | 630/45001 [43:25<51:25:46,  4.17s/it]
> > Epoch 2, global step 11330, total step 450010, train lm loss: 1.8668335244059562
> > ```
> 
> 我是这样理解的，不知道是否准确，在epoch 1内部中，对于每个batch，模型只见过一次数据，而在epoch2中，模型见过两次数据，因此epoch2和epoch1的loss会有一个明显下降，而epoch内部差异不大

多谢，我理解你说的，不过我的问题是，从epoch0结束到epoch1 开始, loss 突然增大了（1.998 -> 2.013),   
从epoch1 -> epoch2, loss 瞬间增大尤为明显（1.7021038860082627 -> 1.8552434042096138）。 
就是从一个epoch结束进入下一个epoch, loss 瞬间增大，这个不太知道什么原因？

....................


Epoch 1, global step 11130, total step 450010, train lm loss: 1.7039588585495948）

**Comment by JJack0812** [comment]
@zmingshi 你好，我想请教一下。我也跟您一样使用了相同的训练模板：`散文+<eod>`，但是**加载了预训练权重**和**随机初始化参数**两种情况下，初期的loss几乎一致，在8左右。
**应该是没加载错**：我在训练代码里加载了预训练权重之后打印了参数，和单独写脚本打印权重参数，打印结果是一致的。
想问下您训练散文的loss是修改代码之后直接变得很小吗？还是慢慢降下去的（感觉像是从头训练了）？能分享一下吗？不胜感激！
可以通过邮箱联系我：jianshu.chen[AT]qq.com

**Comment by JJack0812** [comment]
> @zmingshi 你好，我想请教一下。我也跟您一样使用了相同的训练模板：`散文+<eod>`，但是**加载了预训练权重**和**随机初始化参数**两种情况下，初期的loss几乎一致，在8左右。
> **应该是没加载错**：我在训练代码里加载了预训练权重之后打印了参数，和单独写脚本打印权重参数，打印结果是一致的。
> 想问下您训练散文的loss是修改代码之后直接变得很小吗？还是慢慢降下去的（感觉像是从头训练了）？能分享一下吗？不胜感激！
> 可以通过邮箱联系我：jianshu.chen[AT]qq.com

啊仔细看了下我是用fp16训练的，fp32的loss就比较正常了，在2.5左右

**Comment by JJack0812** [comment]
> @zmingshi 你好，我想请教一下。我也跟您一样使用了相同的训练模板：`散文+<eod>`，但是**加载了预训练权重**和**随机初始化参数**两种情况下，初期的loss几乎一致，在8左右。
> **应该是没加载错**：我在训练代码里加载了预训练权重之后打印了参数，和单独写脚本打印权重参数，打印结果是一致的。
> 想问下您训练散文的loss是修改代码之后直接变得很小吗？还是慢慢降下去的（感觉像是从头训练了）？能分享一下吗？不胜感激！
> 可以通过邮箱联系我：jianshu.chen[AT]qq.com

啊我是用了fp16, 仔细阅读了仓库的README之后改成了fp32就正常啦...
