### ISSUE TITLE
使用基于STC数据集修改的代码跑问题生成

### ISSUE THREAD

**Issue by LaVineChan** [TsinghuaAI/CPM-1-Finetune#24]
我使用基于STC数据集修改的代码做问题生成任务，现在训练集上loss能正常下降，但是验证集上loss和PPL都为nan，请问作者知道是什么原因吗？

**Comment by t1101675** [comment]
请问您验证集上面的评测方式和训练集是否一样？建议可以切一部分训练集当成验证集看一下 loss 的情况，确保不是评测的问题。

**Comment by fangd123** [comment]
@LaVineChan 我也遇到了类似的问题，你可以尝试改变一下batch_size的大小，看看能否解决

**Comment by acst1223** [comment]
我也遇到了类似的问题，经过排查发现了原因：在finetune_lm.py的64-67行处，针对samples分割的最后一部分有如下的处理：
```
while start + self.seq_length + 1 < len(token_ids):
    samples.append(token_ids[start: start + self.seq_length + 1])
    start = start + self.seq_length + 1
samples.append(token_ids[start:] + [self.pad_id] * (self.seq_length + 1 - (len(token_ids) - start)))
```
这一段代码是把每一段分成长度为self.seq_length+1（即最大长度+1）的片段。每个片段的前self.seq_length个字符作为输入，后self.seq_length个字符作为label。
对于最后一个片段，如果有效的token数只有1，那么会导致label全部被mask，导致loss可能为nan。
要避免这个问题，可以给最后一行加一个判断：
```
if len(token_ids) - start > 1:
    samples.append(token_ids[start:] + [self.pad_id] * (self.seq_length + 1 - (len(token_ids) - start)))
```
