### ISSUE TITLE
 [deepspeed] fp16 dynamic loss scale overflow! 

### ISSUE THREAD

**Issue by 520jefferson** [TsinghuaAI/CPM-1-Finetune#28]
对话finetune进行到1.1个epoch是遇到了这个问题。

![image](https://user-images.githubusercontent.com/5691554/120164506-3bf28b00-c22d-11eb-87f7-4690f045b2cc.png)

train loss从1.6以下变到80多

**Comment by t1101675** [comment]
dynamic loss overflow 是混合精度训练时候的正常现象，程序会自动调整 loss scale，具体可参考 https://arxiv.org/abs/1710.03740。loss 变到 80多应该和这个没有关系

**Comment by 520jefferson** [comment]
> dynamic loss overflow 是混合精度训练时候的正常现象，程序会自动调整 loss scale，具体可参考 [https://arxiv.org/abs/1710.03740。loss](https://arxiv.org/abs/1710.03740%E3%80%82loss) 变到 80多应该和这个没有关系

@t1101675  我后来把 loss_scale 改为dynamic的方式从跳变前的loss 1.66的，作为初始化结果loss 从2.27开始了，这个合理吗？

另外，我想测试下模型的多轮对话，我看<sep>分隔多句，这个是选项的预训练，我直接用空格进行了context的拼接，是否合理？还是说我需要采用<sep>分隔这样有利于embedding层面有区分性，会好很多呢？
