### ISSUE TITLE
如何微调自己的数据集

### ISSUE THREAD

**Issue by zhenhao-huang** [TsinghuaAI/CPM-1-Finetune#3]
如何微调自己的数据集，能否用单卡或者双卡进行微调，微调时怎么才能占用显存最小

**Comment by t1101675** [comment]
1. 微调自己的数据集需要根据您的任务格式设计模板。我们目前只提供了 ChID 成语填空这个数据集的模板。其他任务的模板（如 NLI 任务，QA 任务）我们之后会陆续放出。
2. small 模型和 medium 模型可以使用单卡进行微调（但是 batch size 也要相应地减小）。large 模型的默认参数是使用两张卡存一套模型参数，因为在我们的机器上一张卡放不下，所以两张卡可以，一张卡不行。如果您有显存更大的机器，可以把 finetune_chid_large.sh 中的 MPSIZE 改为1，便可以在一张卡上跑了。
3. 我们现在还没有考虑对显存占用的优化，一些经验是，在保持每张卡 batch_size 不变的情况下，使用更多卡训练可以使得每张卡的显存占用更少，原因是 deepspeed 内部进行了一些优化。另外，也可以通过限制一下输入序列的长度来减少显存占用。

**Comment by uk9921** [comment]
开发者您好，请问对于分类任务应该怎么求label？
场景：假如对分类任务做zero-shot，数据的样例是 {"query": query_i, "label": label_i}，label的范围是labels(label_0~label_n)。
我想到了两种方法：
方法1. 假如有query_i，计算 “这是关于${label_k}的文章：query_i” 在label scope的loss值：
```
label_loss_map = {}
for label_k in labels:
   # 对模版“这是关于${label_k}的文章：query_i”计算loss值
   label_loss_map[label_k] = loss(“这是关于${label_k}的文章：query_i”)
min_loss_label = min(label_loss_map.items(), key=lambda x: x[1])[0]
predict_label = min_loss_label
```
方法2. 假如有query_i，cpm模型+dense分类层，然后冻结cpm模型对dense分类层进行训练。

请问开发者是如何使用cpm对分类任务进行预测的？谢谢！

**Comment by t1101675** [comment]
我们是使用方法1做的，具体做法可以参考我们的技术报告 https://arxiv.org/pdf/2012.00413.pdf，和您说的非常类似。当然这也不是唯一的选择，如果您尝试了更好的方法，欢迎交流 : )

**Comment by t1101675** [comment]
我们是使用方法1做的，具体做法可以参考我们的[技术报告](https://arxiv.org/pdf/2012.00413.pdf)，和您说的非常类似。当然这也不是唯一的选择，如果您尝试了更好的方法，欢迎交流 :

**Comment by t1101675** [comment]
我们是使用方法1做的，具体可以参考我们的[技术报告](https://arxiv.org/pdf/2012.00413.pdf)，和您说的非常类似。当然这也不是唯一的做法，如果您尝试了更好的方法，欢迎交流 😄

**Comment by uk9921** [comment]
感谢回复～后面我粗略的测试了一下方法1做zero-shot情感多分类实验，不同模版的结果如下：

> 1 . 这是关于情绪${label_k}的文章：query_i,  acc 29.2%
> 2. 这是关于${label_k}的文章：query_i,  acc 18.7%
> 3. query_i的情绪是：${label_k},  acc 23.5%
> 4. ${label_k} -> query_i,  acc 22.3%
> 5. query_i -> ${label_k},  acc 12.7%
> 6. ${label_k}情绪 -> query_i,  acc  26.3%

看起来不同的模版的分类结果有很大的差距，我阅读了CPM的技术报告，和报告里面最为相似的模版取得了最优解。
请问模版和pre-train的数据有关吗，开发者在选择下游任务模版的时候，可以根据什么经验可以选出优质模版？

**Comment by zmingshi** [comment]
@t1101675  您好，我想做一下文本生成的finetune， 利用`pretrain_gpt2.py` 好一点 还是 `finetune_child.py `基础上修改好呢？
看技术报告，生成任务finetune 采用了pretrain 类似的超参数，pretrain 使用的运行超参数脚本可以提供下吗？
非常感谢！

**Comment by zhenhao-huang** [comment]
> 1. 微调自己的数据集需要根据您的任务格式设计模板。我们目前只提供了 ChID 成语填空这个数据集的模板。其他任务的模板（如 NLI 任务，QA 任务）我们之后会陆续放出。
> 2. small 模型和 medium 模型可以使用单卡进行微调（但是 batch size 也要相应地减小）。large 模型的默认参数是使用两张卡存一套模型参数，因为在我们的机器上一张卡放不下，所以两张卡可以，一张卡不行。如果您有显存更大的机器，可以把 finetune_chid_large.sh 中的 MPSIZE 改为1，便可以在一张卡上跑了。
> 3. 我们现在还没有考虑对显存占用的优化，一些经验是，在保持每张卡 batch_size 不变的情况下，使用更多卡训练可以使得每张卡的显存占用更少，原因是 deepspeed 内部进行了一些优化。另外，也可以通过限制一下输入序列的长度来减少显存占用。

非常感谢您的回复。
1.large的模型参数是不是对应CPM-Generate训练好的模型参数（26亿），如果我想在cpm模型基础上进行微调，把CHECKPOINT_PATH路径改为cpm模型存放路径就可以了吗？您加载large模型的两张卡都是3090 24G吗？（从我的两张2070 8G,一张1070 8G,一张1050 4G,共四卡28G来看，都跑不动large模型。在跑small模型时，我还发现不同算力的显卡无法一起并行运算）
2.finetune.py保存的step是best_step，那acc是否也应该保存best_acc？得到最优
3.如何测试微调完成后的结果

**Comment by t1101675** [comment]
@uk9921 模板可能跟数据有关，但是我们的数据并没有经过特殊的处理。我们在选择下游任务模板的时候确实也尝试了很多种方法，但是对于如何找到优质模板也没有很好的经验。

**Comment by lichen222** [comment]
同问，请问微调自己的数据集的时候是需要把自己的数据集转化成跟ChID一样格式的吗，如果是的话，该怎么转化呢

**Comment by t1101675** [comment]
不需要转化成和 ChiD 一样的格式。可以参照 preprocess_chid_finetune.py 中 Template 的注释内容根据您原来的输入格式设计模板，只需要保证模板合理即可。几种常见任务的模板在我们的技术报告中都有描述。

**Comment by t1101675** [comment]
> > 1. 微调自己的数据集需要根据您的任务格式设计模板。我们目前只提供了 ChID 成语填空这个数据集的模板。其他任务的模板（如 NLI 任务，QA 任务）我们之后会陆续放出。
> > 2. small 模型和 medium 模型可以使用单卡进行微调（但是 batch size 也要相应地减小）。large 模型的默认参数是使用两张卡存一套模型参数，因为在我们的机器上一张卡放不下，所以两张卡可以，一张卡不行。如果您有显存更大的机器，可以把 finetune_chid_large.sh 中的 MPSIZE 改为1，便可以在一张卡上跑了。
> > 3. 我们现在还没有考虑对显存占用的优化，一些经验是，在保持每张卡 batch_size 不变的情况下，使用更多卡训练可以使得每张卡的显存占用更少，原因是 deepspeed 内部进行了一些优化。另外，也可以通过限制一下输入序列的长度来减少显存占用。
> 
> 非常感谢您的回复。
> 1.large的模型参数是不是对应CPM-Generate训练好的模型参数（26亿），如果我想在cpm模型基础上进行微调，把CHECKPOINT_PATH路径改为cpm模型存放路径就可以了吗？您加载large模型的两张卡都是3090 24G吗？（从我的两张2070 8G,一张1070 8G,一张1050 4G,共四卡28G来看，都跑不动large模型。在跑small模型时，我还发现不同算力的显卡无法一起并行运算）
> 2.finetune.py保存的step是best_step，那acc是否也应该保存best_acc？得到最优
> 3.如何测试微调完成后的结果

我们仔细 check了 一下：
1. 我们的两张卡都是32G 的 V100，3090 24G 可能不太够。我们没有试过用不同算力的显卡一起计算，如果不是内存溢出的原因，还希望您能提供更多的信息。
2. 是的，已经修复这个问题。
3. 测试的方法 README.md 2.2 中作了说明。

**Comment by zmingshi** [comment]
> 不需要转化成和 ChiD 一样的格式。可以参照 preprocess_chid_finetune.py 中 Template 的注释内容根据您原来的输入格式设计模板，只需要保证模板合理即可。几种常见任务的模板在我们的技术报告中都有描述。

麻烦问下
1. 如果想finetune 上文生成下文的任务的话怎么处理训练数据好一点呢？我目前是 `上文: paragraph1 下文: paragraph2` 这样。不知道这个训练模版上你有什么建议？
2. 计算loss 的时候需要计算 `上文: paragraph1 下文: paragraph2`这一完整输入数据呢，还是只考虑要生成的结果 `paragraph2` 呢？
3. 现在的finetune 代码都是数据直接load 到内存，如果训练数据比较大，有什么好的办法或者代码可以参考吗？

**Comment by zhenhao-huang** [comment]
@t1101675 
1.我查阅了一下这是pytorch的问题，pytorch先分配显存，再检查显卡的算力是否相同。如果显存足够，显卡不同就会报RuntimeError: CUDA error: no kernel image is available for execution on the device的错，使用相同算力显卡就可以正常运行。
2.我也是做文本生成的微调，一般文本生成的模板是：<cls>文本内容<sep>，词表中没有<cls>的token，可否用<eod>代替<cls>？<eod>在CPM的词表中表示的是？
3.如果CPM可以用 <cls>文本内容<sep> 这个模板做文本生成的微调，通过预测下一个词的label计算loss是否可行？

**Comment by uk9921** [comment]
@zhenhao-huang
eod是end of token，不可以当分隔符

**Comment by zhenhao-huang** [comment]
@uk9921 用什么充当分隔符比较合适

**Comment by lichen222** [comment]
> 不需要转化成和 ChiD 一样的格式。可以参照 preprocess_chid_finetune.py 中 Template 的注释内容根据您原来的输入格式设计模板，只需要保证模板合理即可。几种常见任务的模板在我们的技术报告中都有描述。

谢谢您，那请问要修改成适用于自己数据集的模板需要修改哪些地方呢，我自己修改了一下跑不通，比如纯文本的模板，没有chid中的truth

**Comment by zhenhao-huang** [comment]
@lichen222 我是用`文本内容<sep>文本内容<sep>文本内容<sep>`这个模板做文本生成的,在微调chid的代码基础上进行修改:

1. 修改preprocess_chid_finetune.py,生成适合自己数据集的id,可以参考chid的数据格式(要注意限制输入训练长度)
2. 修改finetune_chid.py中对应的数据处理
3. 由于我做的是文本生成,所以我没有去计算acc,也就没有用到finetune_chid.py中的evaluate函数

**Comment by zhenhao-huang** [comment]
@t1101675 我想问下,做文本生成微调多少个epoch比较合适?

**Comment by zmingshi** [comment]
> @t1101675 我想问下,做文本生成微调多少个epoch比较合适?

你做文本生成，lr 设置是多少呢？最后loss 下降到多少了？我的loss 下降非常慢～

**Comment by zmingshi** [comment]
> @t1101675 我想问下,做文本生成微调多少个epoch比较合适?

@zhenhao-huang 麻烦问下，你做文本生成，lr 设置是多少呢？最后loss 下降到多少了？我的loss 下降非常慢～

**Comment by LaVineChan** [comment]
> @lichen222 我是用`文本内容<sep>文本内容<sep>文本内容<sep>`这个模板做文本生成的,在微调chid的代码基础上进行修改:
> 
> 1. 修改preprocess_chid_finetune.py，生成适合自己数据集的id，可以参考chid的数据格式(要注意限制输入训练长度)
> 2. 修改finetune_chid.py中对应的数据处理
> 3. 由于我做的是文本生成，所以我没有去计算acc，也就没有用到finetune_chid.py中的evaluate函数，只留下loss做指标
请问一下你限制输入训练长度是如何实现的（除了设置最大输入长度）

**Comment by LaVineChan** [comment]
> @lichen222 我是用`文本内容<sep>文本内容<sep>文本内容<sep>`这个模板做文本生成的,在微调chid的代码基础上进行修改:
> 
> 1. 修改preprocess_chid_finetune.py，生成适合自己数据集的id，可以参考chid的数据格式(要注意限制输入训练长度)
> 2. 修改finetune_chid.py中对应的数据处理
> 3. 由于我做的是文本生成，所以我没有去计算acc，也就没有用到finetune_chid.py中的evaluate函数，只留下loss做指标

请问一下您，限制输入训练长度是如何实现的（就是通过限制MAXSEQLEN吗）

**Comment by zhenhao-huang** [comment]
@zmingshi lr是`0.00001`，大部分训练参数没怎么改。step大概训练到100多loss就开始下降到1以下，我的loss是从20左右起步，后面基本接近于0。

**Comment by zhenhao-huang** [comment]
@LaVineChan 脚本里面的`MAXSEQLEN`参数我不清楚怎么改，所有没有改这个参数，似乎这个参数改了没什么影响。限制输入训练长度我是在转id的时候做了个判断，保证每一条训练数据不超过`max_length`超参数，并且结尾是`<sep>`的token

**Comment by zmingshi** [comment]
> @zmingshi lr是`0.00001`，大部分训练参数没怎么改。step大概训练到100多loss就开始下降到1以下，我的loss是从20左右起步，后面基本接近于0。

@zhenhao-huang 多谢哈！100个step loss 就到1 了？batch_size 多大呢？你的收敛好快呀～ 我过了一个epoch loss 还是很高，不过的生成比较难，输入信息比较少～
话说 你的结尾符号是  ` <sep> `？ 不是 `<eod>`吗？

**Comment by zhenhao-huang** [comment]
@zmingshi 个人理解是主要取决于你做的任务类型，相同类型的用`<sep>`，不同类型的用`<eod>`

**Comment by zmingshi** [comment]
> @zmingshi 个人理解是主要取决于你做的任务类型，相同类型的用`<sep>`，不同类型的用`<eod>`。batch_size是1

了解了，多谢！

**Comment by zmingshi** [comment]
> @zmingshi 个人理解是主要取决于你做的任务类型，相同类型的用`<sep>`，不同类型的用`<eod>`。batch_size是1

非常感谢！你的batch_size=1, 所以你的seq_length 很长是吧？长文生成吗？

**Comment by zhenhao-huang** [comment]
@zmingshi 短文本生成，我做了最大输入训练限制。修改了`loss_mask`的取值，目前`loss`没有过快收敛，参考#16

**Comment by LaVineChan** [comment]
> @zmingshi 个人理解是主要取决于你做的任务类型，相同类型的用`<sep>`，不同类型的用`<eod>`。batch_size是1
这个不同类型是指什么？比如我要做的是问题生成的任务，我要组成(context:answer:question)的三元组，那context和anwser之间适合放<sep>还是<eod>

**Comment by LaVineChan** [comment]
> @zmingshi 个人理解是主要取决于你做的任务类型，相同类型的用`<sep>`，不同类型的用`<eod>`。batch_size是1

这个不同类型是指什么？比如我要做的是问题生成的任务，我要组成(context:answer:question)的三元组，那context和anwser之间适合放还是

**Comment by LaVineChan** [comment]
> @zmingshi 个人理解是主要取决于你做的任务类型，相同类型的用`<sep>`，不同类型的用`<eod>`。batch_size是1

这个不同类型是指什么？比如我要做的是问题生成的任务，我要组成(context:answer:question)的三元组，那context和anwser之间适合放<sep>还是<eod>

**Comment by zhenhao-huang** [comment]
@LaVineChan context和anwser之间应该不用吧，answer之后接’<eod>’

**Comment by zmingshi** [comment]
> @zmingshi 短文本生成，我做了最大输入训练限制。batch_size为1，主要是我显存不够。修改了`loss_mask`的取值，目前`loss`没有过快收敛，参考#16

@zhenhao-huang 多谢！刚看到你另一个帖子～  我现在的 `loss_mask = [1] * (len(d) - 1)`，也就是全是1，你现在也是这个loss_mask 吧，我用这个loss_mask loss 从10点多降低到 5.2 左右就很难降低了～ 不过我看作者在这个帖子#16 最后提示是不是 input 部分不用计算loss, 只有计算 output 的loss 会好一些？不知道你有做过尝试吗？

**Comment by zhenhao-huang** [comment]
@zmingshi 
1.是的，我训练的`loss`从13左右下降到接近于0。
2.这个没有尝试过，不太清楚

**Comment by zmingshi** [comment]
> @zmingshi
> 1.是的，我训练的`loss`从13左右下降到接近于0。
> 2.这个没有尝试过，不太清楚

@zhenhao-huang 多谢回复，所以你一直用的 `loss_mask = [1] * (len(d) - 1)` 是吧？我现在打算试着把input mask 掉，只算output 的loss，不知道咋样～训训看了

**Comment by blueseasky** [comment]
> 我们是使用方法1做的，具体可以参考我们的[技术报告](https://arxiv.org/pdf/2012.00413.pdf)，和您说的非常类似。当然这也不是唯一的做法，如果您尝试了更好的方法，欢迎交流 😄

请教一下，如果是针对分类任务做非zero-shot，finetune的时候模板如何设置比较好呢？（个别分类任务类别数比较多）是不是只能选择 cpm模型+dense分类层 这种方式？

**Comment by t1101675** [comment]
如果类别数比较多，建议选择 cpm模型+dense分类层 这种方式

**Comment by blueseasky** [comment]
> 如果类别数比较多，建议选择 cpm模型+dense分类层 这种方式
@t1101675  请教下，我看词典里有存比如10、11、12这样的数字，在构造词典的时候是特意加入了自然数吗？如果是的话 大概加入了什么范围的数字？

**Comment by zhenhao-huang** [comment]
微调文本生成建议使用`fp32`精度，`短文本生成`和`长文本生成`模板可以分别参考`文本内容<eod>文本内容<eod>...文本内容<eod>文本内容<eod>`和`文本内容`，文本生成结果可看：https://github.com/zhenhao-huang/CPM-1-Finetune-Text-Generation/tree/main

**Comment by 447428054** [comment]
@zmingshi @zhenhao-huang 
你好，CPM模型能分享一下吗

https://cpm.baai.ac.cn/这个链接打不开了呢

**Comment by t1101675** [comment]
新的模型链接：https://model.baai.ac.cn/model-detail/100017
