### ISSUE TITLE
 How to load the checkpoint if I am not using deepspeed?

### ISSUE THREAD

**Issue by Walid-Ahmed** [TsinghuaAI/CPM-1-Finetune#30]
How can I load the checkpoint if I am not using deepspeed?
 cpm_small_4k_stc_3ep/iter_0004000/mp_rank_00/model_optim_rng.pt

**Comment by zzy14** [comment]
Hi, you can use [transformers](https://huggingface.co/TsinghuaAI/CPM-Generate) instead of this repo.
