### ISSUE TITLE
关于微调超长文本和生成结果的问题

### ISSUE THREAD

**Issue by zhenhao-huang** [TsinghuaAI/CPM-1-Finetune#31]
1.经过我的测试，输入训练的最大长度为1025。现在我想微调超长文本生成，类似于小说，由于输入训练长度最大为1025，那是不是就无法微调超长文本？
2.在相同代码，相同环境，不同显卡下的生成结果不一致。

**Comment by t1101675** [comment]
1. 是的，CPM-1 有文本输入长度的限制，最长1024。但是 CPM-2 由于使用相对位置编码，没有这个限制，您可以尝试 CPM-2。
2. 这个是合理的。我们在实验中也观察到了这样的现象，因为不同硬件的底层实现有一些差别，可能导致生成的随机数序列不一样，文本生成的结果也就会受影响。但是总体生成质量应该相差不大。

**Comment by zhenhao-huang** [comment]
是的，输入训练的最大长度应为1024，忘了`input_ids`和`labels`是需要`-1`操作。`CPM-2`模型参数实在太大，两张3090估计都无法加载成功，只能远观了:joy:。
