### ISSUE TITLE
多卡finetune时的Bug

### ISSUE THREAD

**Issue by xiaofei05** [TsinghuaAI/CPM-1-Finetune#34]
mpu.get_data_parallel_world_size() == 2 时， 训练到一半loss突然上升：

![image](https://user-images.githubusercontent.com/26503378/124701280-dfb41280-df20-11eb-9e6b-73b894dad644.png)

此时保存的lr_scheduler为：

![image](https://user-images.githubusercontent.com/26503378/124701400-168a2880-df21-11eb-81da-34b1ccaae0ea.png)

如果根据 learning_rates.py 42-43的计算：

```py
  if self.decay_style == self.DECAY_STYLES[0]:
      return self.start_lr*((self.end_iter-(self.num_iters-self.warmup_iter))/self.end_iter)
```
lr将是一个负数，lr的总步数end_iter是单个的data_parallel的总步数，但是在衰减的时候步数被多个data_parallel重复累加了。

**Comment by GongMingGithub** [comment]
@xiaofei05  你的显卡是多大的？我用2个24G的3090，OOM了

**Comment by xiaofei05** [comment]
> @xiaofei05 你的显卡是多大的？我用2个24G的3090，OOM了

我用的4块24G的3090进行模型并行， 2块确实会OOM

**Comment by GongMingGithub** [comment]
@xiaofei05  4张24G的3090进行微调，你用的是fp32还是fp16?你的batch_size设置是多大？4张卡跑是通过--nproc_per_node=4这个参数设置的吗？
