### ISSUE TITLE
zero-shot测试：TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by kevin65050113** [TsinghuaAI/CPM-1-Finetune#39]
deepspeed@cba0d9d3f627:/CPM$ sudo bash scripts/chid/zero-shot_chid_large.sh 
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
using world size: 2 and model-parallel size: 2 
 > using dynamic loss scaling
> initializing model parallel with size 2
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 26051 and data parallel seed: 23333
Traceback (most recent call last):
  File "zero-shot_chid.py", line 236, in <module>
    main()
  File "zero-shot_chid.py", line 169, in main
    test_dataloader, test_dataset = load_data(args, 'test', tokenizer, 1)
  File "zero-shot_chid.py", line 126, in load_data
    dataset = CHIDDataset(args, filename, data_type, tokenizer, ratio=ratio)
  File "zero-shot_chid.py", line 50, in __init__
    self.samples, self.sizes, self.truth_labels = self.process(data)
  File "zero-shot_chid.py", line 55, in process
    contents = data["contents"]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "zero-shot_chid.py", line 236, in <module>
    main()
  File "zero-shot_chid.py", line 169, in main
    test_dataloader, test_dataset = load_data(args, 'test', tokenizer, 1)
  File "zero-shot_chid.py", line 126, in load_data
    dataset = CHIDDataset(args, filename, data_type, tokenizer, ratio=ratio)
  File "zero-shot_chid.py", line 50, in __init__
    self.samples, self.sizes, self.truth_labels = self.process(data)
  File "zero-shot_chid.py", line 55, in process
    contents = data["contents"]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'zero-shot_chid.py', '--local_rank=1', '--data_dir', '/CPM/output', '--model-parallel-size', '2', '--num-layers', '32', '--hidden-size', '2560', '--load', '/CPM/CPM-large-MP1', '--num-attention-heads', '32', '--seq-length', '1024', '--max-position-embeddings', '1024', '--tokenizer-type', 'GPT2BPETokenizer', '--fp16', '--out-seq-length', '512', '--tokenizer-path', 'bpe_3w_new/', '--vocab-size', '30000', '--batch-size', '2', '--deepspeed', '--deepspeed_config', '/CPM/scripts/chid/../ds_config/ds_finetune_large.json', '--seed', '23333', '--results_dir', 'results/', '--model_name', 'zeroshot-large-chid', '--zero_shot']' returned non-zero exit status 1.

deepspeed@cba0d9d3f627:/CPM$ cat scripts/chid/zero-shot_chid_large.sh 
#!/bin/bash

DATA_DIR="/CPM/output"
CHECKPOINT_PATH="/CPM/CPM-large-MP1"
RESULTS_DIR="results/"
MODEL_NAME="zeroshot-large-chid"
TOKENIZER_PATH="bpe_3w_new/"
MPSIZE=2
NLAYERS=32
NHIDDEN=2560
NATT=32
MAXSEQLEN=1024

CUR_PATH=$(realpath $0)
CUR_DIR=$(dirname ${CUR_PATH})
DS_CONFIG="${CUR_DIR}/../ds_config/ds_finetune_large.json"

python3 -m torch.distributed.launch --master_port ${1-1122} --nproc_per_node $MPSIZE zero-shot_chid.py \
       --data_dir ${DATA_DIR} \
       --model-parallel-size ${MPSIZE} \
       --num-layers ${NLAYERS} \
       --hidden-size ${NHIDDEN} \
       --load ${CHECKPOINT_PATH} \
       --num-attention-heads ${NATT} \
       --seq-length ${MAXSEQLEN} \
       --max-position-embeddings 1024 \
       --tokenizer-type GPT2BPETokenizer \
       --fp16 \
       --out-seq-length 512 \
       --tokenizer-path ${TOKENIZER_PATH} \
       --vocab-size 30000 \
       --batch-size 2 \
       --deepspeed \
       --deepspeed_config ${DS_CONFIG} \
       --seed 23333 \
       --results_dir ${RESULTS_DIR} \
       --model_name ${MODEL_NAME} \
       --zero_shot \
deepspeed@cba0d9d3f627:/CPM$

**Comment by t1101675** [comment]
您好！请确认1. 是否用我们的预处理脚本处理数据。2. 处理出来的数据是否与 README 中 3.1 描述的格式一致。

**Comment by kevin65050113** [comment]
已经确认是数据处理的不对导致，谢谢！
