### ISSUE TITLE
cpm-large 的预训练动量是否会开源呢？

### ISSUE THREAD

**Issue by yayaQAQ** [TsinghuaAI/CPM-1-Finetune#50]
rt

**Comment by t1101675** [comment]
目前没有开源计划

**Comment by 447428054** [comment]
@yayaQAQ @Tron1994 你好，请问你基于CPM微调时是怎么加载模型的呢

我看其加载代码中都是有latest_checkpointed_iteration这个文件的

![image](https://user-images.githubusercontent.com/35593767/226100234-e99889ae-2a87-423e-a02d-65b2ab534e17.png)
