### ISSUE TITLE
请问CPM-1预训练的时候是训练1024个token吗

### ISSUE THREAD

**Issue by orlando1986** [TsinghuaAI/CPM-1-Finetune#51]
很多模型支持比如512 token，但是预训练往往都训练个128或者256，这会导致后面没有预训练到的token在微调的时候效果很差。我想请教下cpm是1024个token都训练满了吗

**Comment by zzy14** [comment]
最大文本长度是1024，对于预训练数据里比较长的文档，是塞满1024的。对于塞不满的短文档，会做padding。
